### ISSUE TITLE
New BIOS not booting ATAPI cdrom

### ISSUE THREAD

**Issue by vruppert** [fysnet/i440fx#3]
When I try to boot an old Knoppix image from first ATAPI cdrom at ata0, it shows the Knoppix boot screen, but after pressing enter only the message "Loading linux..." appears and nothing else happens. In the log the message "vector 0xf stuck?" is repeated,
When I attach the first ATAPI cdrom to ata1, the boot fails with failure code 0x0002. Having two harddisks on ata0 and a cdrom on ata1-master is a usual setup for me, but it's not working at all with the new BIOS.

**Comment by fysnet** [comment]
Thanks for letting me know. I will have a look at it.

**Comment by fysnet** [comment]
I had a typo in cdrom.asm. I have committed the change. Please let me know if it now works as expected.

Thank you.

**Comment by vruppert** [comment]
I can confirm that the first stage of booting from ATAPI cdrom now also works if attached to ata1. The boot process still gets stuck after that, but I guess this not related to the boot code, but to the IOAPIC init. All images I have tested hang at the second stage and the log is filled with "[IOAPIC] vector 0xf stuck?". I don't know if the bug is in your code or the Bochs IOAPIC emulation.

**Comment by fysnet** [comment]
I can confirm that too. It doesn't happen with the original BIOS, and I add quite a bit of APIC function that the org BIOS didn't have, so it has to be something with mine. I will have a look. Thanks again.

**Comment by fysnet** [comment]
I made a few fixes and updates. Please check to see if this fixes this issue for you. Thank you again.

**Comment by vruppert** [comment]
The issue is not yet fixed, but the error message has changed:
[APIC0 ] bogus vector 0xf, ignoring ...

Tested ISO files:
Knoppix 6.2.1 (2010)
NetBSD 6.0 (2010)
Ubuntu Linux 23.10 (2023)

**Comment by fysnet** [comment]
Ya, after a few more tests here, I found a similar problem.
If you use
```
cpu: model=pentium
```
do you get the same errors? If not, it is without a doubt my (IO)APIC code.

If you use
```
cpu: model=broadwell_ult
```
you probably get the same errors as you describe.

I will have a look and see what is going on.

**Comment by vruppert** [comment]
With cpu models pentium, pentium_mmx, p2_klamath and p3_katmai the boot hangs without APIC0 messages, the newer models hang with these messages.

**Comment by fysnet** [comment]
Okay. Thank you for checking.

So that I compare with your exact results, do you have a link to an image of any of the three OSes you mentioned, possibly the most common one you tested with? (and maybe smallest in size)
My email address (which you should already have) accepts quite large attachments too.

Thanks again. It is appreciated.

**Comment by fysnet** [comment]
Okay. Try the new cdrom.asm file.
I got it to boot the .iso you sent me.
Thank you.

**Comment by vruppert** [comment]
The NetBSD boot with the new BIOS now shows the same behavior as the Bochs BIOS. With most of the cpu model the boot up to language selection menu works fine, but some 64-bit cpu models reboot after 3rd exception (Bochs issue). The Knoppix Linux live system boots fine to desktop, but Ubuntu Linux installation DVD boot stops with the following message:

[snapshot.txt](https://github.com/user-attachments/files/18114294/snapshot.txt)

With Bochs BIOS the graphical boot logo is shown after a while. Please have a look at ubuntu.com.

**Comment by fysnet** [comment]
Okay, thank you. I will see about getting a ubuntu image and do some tests.
I will close this issue. Please feel free to open a new issue if you find something.
Thank you again.
